apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-1
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook-1
    server: "https://kubernetes.default.svc"
  project: demo-project
  source: 
    path: guestbook
    repoURL: "https://github.com/aadilraza339/udemy-coruse.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true