apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/aadilraza339/udemy-coruse.git
  password: 9873752914raza@
  username: aadilraza339